defaults:
  - _self_  
  - defaults@defaults.hydra: hydra
  - defaults@defaults.email_processing: email_processing
  - defaults@defaults.paths: paths
  - defaults@defaults.analysis: analysis
  - defaults@defaults.visualization: visualization

app:
    name: "JobTrendX"
    version: "0.1.0"
    mode: "development"

# DO NOT CHENGE!
taxonomy_path: "/home/santiago/Documents/MyScripts/JobTrendX/src/jobtrendx/taxonomy"
taxonomy_files:
  locations: locations.yaml
  job_titles: job_titles.yaml
  title_tags: title_tags.yaml
  skills: skills.yaml
  languages: language.yaml
