defaults:
 - paths: paths
 - analysis: analysis
 - visualization: visualization
 - email_processing: email_processing
 - hydra : hydra

app:
    name: "JobTrendX"
    version: "0.1.0"
    mode: "development"
